server {
    listen 80;
    server_name cctplattsburgh.org www.cctplattsburgh.org;
    add_header Content-Security-Policy "upgrade-insecure-requests";

    # Static file handling for other requests
    location /about {
        root /usr/share/nginx/html;
        try_files $uri /about/index.html;
    }

    location /contact {
        root /usr/share/nginx/html;
        try_files $uri /contact/index.html;
    }

    location /events {
        root /usr/share/nginx/html;
        try_files $uri /events/index.html;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }
}