server {
    listen 80;
    server_name cctplattsburgh.org www.cctplattsburgh.org;
    add_header Content-Security-Policy "upgrade-insecure-requests";

    # Static file handling for other requests
    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }
}